### ISSUE TITLE
[Bugfix]: fix the user inputs values to following template files.

### ISSUE THREAD

**Issue by mkorat1717** [gregswindle/generator-android-library#5]
Following files found hard corded values about application package and app name. 

generators/app/templates/library/src/main/res/values/strings.xml
generators/app/templates/library/src/main/_AndroidManifest.xml

Please apply the fix to replace hard-corded values.

**Comment by gregswindle** [comment]
Hey, @mkorat1717, it looks like the `develop` and `master` branches have ERB-style template delimiters with variables for some of those files in the `sample` directory, already:

* [`master/generators/app/templates/sample/src/main/res/values/_strings.xml`](https://github.com/gregswindle/generator-android-library/blob/master/generators/app/templates/sample/src/main/res/values/_strings.xml)
* [`master/generators/app/templates/sample/src/main/_AndroidManifest.xml`](https://github.com/cesarferreira/generator-android-library/blob/master/generators/app/templates/sample/src/main/_AndroidManifest.xml)

Those might be a good start. :runner:

**Comment by mkorat1717** [comment]
Fixed is applied and merged under develop branch.

**Comment by gregswindle** [comment]
@mkorat1717 can we close this issue?

**Comment by mkorat1717** [comment]
Absolutely. [Reference #6 ]
